### ISSUE TITLE
クレッシブボルト、ゲイルストームにカラミティゲイルの効果が乗らない

### ISSUE THREAD

**Issue by tousei-seiso** [roratorio-hub/ratorio#105]
クレッシブボルト、ゲイルストームにカラミティゲイルの効果が乗らないので、効果が乗るように修正しプルリクエストを上げておきました。

**Comment by usachoco** [comment]
#103 
#106

**Comment by usachoco** [comment]
ゲイルストームにクリティカルを適用する必要があるのでまだオープンしておきます

**Comment by tousei-seiso** [comment]
[#117](https://github.com/roratorio-hub/ratorio/pull/117)
で、カラミティゲイル状態でのゲイルストームのクリティカル計算を追加しました。

**Comment by usachoco** [comment]
リリース後、問題無いと思いますのでクローズします
