### ISSUE TITLE
覚醒ヤファ靴セットのMDEF加算がおかしい問題

### ISSUE THREAD

**Issue by usachoco** [roratorio-hub/ratorio#108]
Googleフォームからお寄せ頂いた情報です

>覚醒ヤファ靴にヤファｃを刺しただけでＭＤＥＦ２００になります。
セット効果が靴とカードで２重に乗ってるのかも？

**Comment by fueljcl** [comment]
この件ですけど、手持ちのデータでもまっさらなデータでも200になることがないんです
再現手順を確認した方がいいかもしれません

**Comment by fueljcl** [comment]
もしかして…
Lv100以上でInt+10とMdef+10されるんですけど
Int成分で原産Mdef+10ずつ、MdefUP成分で除算Mdefが+10ずつされるのを
+10で合わせて+200と表現している可能性？

it's not bug！

**Comment by usachoco** [comment]
確認ありがとうございました
仰るとおり計算機では減算Def+100と除算Def+100の効果が正しく発揮されていますね
Q&AにBugではないことを確認した旨を掲載するつもりです
それでもし追加でバグの再現手順が来るようなら改めて考えましょうか

**Comment by usachoco** [comment]
Q&Aに掲載したのでしばらくたったらクローズ予定です
1/27ぐらいを目処に
