### ISSUE TITLE
URL入力時に、基本ステータスの「職業」欄の表示がリストでの選択状態と不一致となる

### ISSUE THREAD

**Issue by tousei-seiso** [roratorio-hub/ratorio#11]
再現の手順です：
１．何らかの職を手入力し、キャラクターデータを保存する。
２．何らかの別の職のキャラクターデータをURL入力から読み込む。
３．２．でURL入力で読み込んだ職の、基本ステータスの「職業」欄に、１．で作成した職の名前が表示されたままになる。
※このとき、「職業」欄の右の▼をクリックしてリストを開くと、URL入力したキャラクターの職が正しく選択状態になっています。リストをたたむと、１．で作成した職の名前になっている・・・という状態です。

「職業」欄以外の部分は、URL入力時に正しく更新されているように見えます。

お時間のあるときに見ていただければ・・・。

**Comment by usachoco** [comment]
- 画面上部のロードボタン
- 画面上部のURL入力ボタン
- 画面下部のURL入力ボタン

この全てにドロップダウンリストの再レンダリング関数をトリガーする処理を追加しました
ada2810298fe2eb64a8486d900e48df6491bb1af
