### ISSUE TITLE
Res, Mresが対人に与える影響を計算したい

### ISSUE THREAD

**Issue by usachoco** [roratorio-hub/ratorio#118]
Googleフォームからお寄せ頂いた要望です

>本家のラトリオでも未実装でしたが対人設定でMRES　RESを導入していただけると非常に喜ぶ人がたくさんいると思いますのでよろしくお願いいたします！

個人的にもこれは追加されてほしいと思います

**Comment by fueljcl** [comment]
#58 と同じように拡張する感じで対応でしょうか？

**Comment by usachoco** [comment]
おそらくそうですね

対モンスターではRes, Mresが既に計算されていると思いますから
同じ処理を流してあげられたら楽でよいなと期待しています

**Comment by fueljcl** [comment]
#129 にて #58 とセットで対応
検証待ち

**Comment by usachoco** [comment]
現時点では #129 がエラーを出す場合が確認されています

選択肢を増やす意味で #136 を提案しましたが
セーブデータの拡張に成功するならそれがベストだと思いますし
この Issue は急ぎではないと思いますので
じっくり取り組めたらと思います

**Comment by usachoco** [comment]
#129 で新しいアプローチを検証中

**Comment by usachoco** [comment]
#156 で master にマージしました
