### ISSUE TITLE
装備欄の入力切り替えボタンを使うと表示が以前のものに戻ってしまう

### ISSUE THREAD

**Issue by fueljcl** [roratorio-hub/ratorio#13]
装備欄の「入力切り替え」ボタンを使用すると、カードやエンチャントのプルダウンメニューが以前の表示に戻ります。
また、エンチャントについてはソートタイプの新しいメニューよりも、以前のエンチャントが分かるメニューの方がわかりやすいように感じました。
カードの部分は新しいリストの方が便利に感じますが、ここも「入力切り替え」ボタンを押すことで以前のリストに戻ります。

ご検討のほどよろしくお願い致します。

**Comment by usachoco** [comment]
ありがとうございます
そのボタンを使ったことが無くて気づきませんでした
表示不具合は修正済みです
cbfc17a2099298f93a27b4f07af881ef43fa6259

エンチャントのドロップダウン表示についてはそんな気がしていますが
アウェイキングブルームに存在する大量のエンチャントを見ると少し迷います
一旦検討させていただきます

**Comment by usachoco** [comment]
エンチャントのドロップダウンリストを以前のデザインに戻しました
7754be5b7158e21209ff3a05125ecbd6ed2c276e
