### ISSUE TITLE
ダメージインターバルと存続時間設定の設置スキルの計算結果が合わない部分がある

### ISSUE THREAD

**Issue by tousei-seiso** [roratorio-hub/ratorio#163]
・「実ダメージ」欄の秒間ダメージ
・「攻撃回数」欄の攻撃完了までにかかる時間
の部分が、合わないようです。

**Comment by usachoco** [comment]
#165

**Comment by usachoco** [comment]
現在、dev ブランチはダメージ表示機能の改修で占有しています

**Comment by usachoco** [comment]
## 確認されているエラー
- CBattleCalcResultAll.js:90 Uncaught ReferenceError: InstObjArray is not defined at CBattleCalcResultAll.js:90:1

**Comment by usachoco** [comment]
## 変更前

![Image](https://github.com/roratorio-hub/ratorio/assets/149866018/c7768bac-f9f5-4905-96e9-6f2e40355975)


## 変更後

![Image](https://github.com/roratorio-hub/ratorio/assets/149866018/696c3b44-30d5-4727-849b-d835789a3590)

**Comment by usachoco** [comment]
e5c1dd7029dec5245f63ba061caeb1db665237bf で暫定処理コードを除去しました
その後の検証にも問題は見受けられません

## 検証結果
[Lv200 マイスター Str130 マキシマイズパワーON ギアON](https://roratorio-hub.github.io/ratorio/ro4/m/calcx.html?cx1cy1xv80x21011101.7cz11.413dcz12.41j1cz13.418ecz14.41f3cz15.41gccz16.41h7cz17.41j7cz18.41jdcz19.41k6cz1a.41k6cz1b.4hM1cz1c.4hOacA1Z_1127456b89a3cA128c0cC1.ecD1.f48011cQ19o0gi46cR1.4e7cW100B3x2cZ121)

### 設置スキルではない & 多段Hitするがクールタイムがないスキルの検証
- ◯ トリプルレーザー（性能カスタマイズでCTを0にする）

### 設置スキルではない & 多段Hitしないがクールタイムを持つスキルの検証
- ◯ ラッシュクエイク

**Comment by usachoco** [comment]
dev の検証を開始しています
完了したら master へマージする PR を出します

**Comment by usachoco** [comment]
問題はないと思います
更新履歴などを整備したうえで dev から master への PR を作成します

### コンソールに不審なログが出ない
- ◯ 画面初期化時
- ◯ 単発スキルダメージ計算時
- ◯ 設置スキルダメージ計算時

### 動作が重くならない
- ◯ Sユンケア vs スイフトトラップ (13,513,514 hit必要)
- ◯ Sユンケア vs ゲイルストーム (194,705 hit必要)
- ◯ Sユンケア vs サイキックウェーブ (1,000,000,000 hit必要)

### 800x600の解像度でもレイアウトが大きく崩れない
- ◯ 基本ステータス欄
- ◯ 特性ステータス欄
- ◯ 装備欄
- ◯ アイテム情報欄
- ◯ シャドウ装備欄
- ◯ 習得スキル欄
- ◯ パッシブ持続系欄
- ◯ １次職支援欄
- ◯ ２次職支援欄
- ◯ ３次職支援欄
- ◯ ４次職支援欄
- ◯ ダメージ計算欄

### 旧バージョンで全チェックしているセーブデータを正しくロードできる
- ◯
