### ISSUE TITLE
設置スキルの修正

### ISSUE THREAD

**Issue by usachoco** [roratorio-hub/ratorio#196]
#163 を完了させるための前提タスク

やるべきこと
1. [済] 設置スキルの洗い出し
2. [済] 修正対象スキルの特定
3. [済] 修正作業
4. [済] 修正前後のダメージ差異確認

**Comment by usachoco** [comment]
### 1. 設置スキルの洗い出し
- ドラゴンナイト
    - ダメージインターバルを持つ設置スキルなし
- アークメイジ
    - グラビテーションフィールド
    - ストームガスト
    - ロードオブヴァーミリオン
    - ストラタムトレマー
    - トルネードストーム
    - レインオブクリスタル
    - フローラルフレアロード
    - バイオレントクエイク
    - オールブルーム
    - アストラルストライク
    - ミステリーイリュージョン
    - ダメージインターバルを持たない設置スキルのため修正対象外
        - ファイアーウォール
        - ファイアーピラー
    - 特殊な処理が行われているため修正を保留
        - メテオストーム
- ウィンドホーク
    - ソリッドトラップ
    - ディープブラインドトラップ
    - フレイムトラップ
    - スイフトトラップ
- カーディナル
    - サンクチュアリ
    - マグヌスエクソシズム
    - ニューマティックプロセラ
- マイスター
    - 特殊な処理が行われているため修正を保留
        - マグマイラプション
- シャドウクロス
    - ダメージインターバルを持つ設置スキルなし
- インペリアルガード
    - クロスレイン
- エレメンタルマスター
    - サイキックウェーブ
    - クラウドキル
    - コンフラグレーション
    - ライトニングランド
    - ベナムスワンプ
    - ダメージインターバルを持たない設置スキルのため修正対象外
        - エレクトリックウォーク
        - ファイアーウォーク
- トルバドゥール＆トルヴェール
    - シビアレインストーム
    - 固定ダメージのため修正を保留
        - 不協和音
- インクイジター
    - ダメージインターバルを持つ設置スキルなし
- バイオロ
    - デモンストレーション
    - デモニックファイアー
    - アシディファイドゾーン（地）
    - アシディファイドゾーン（水）
    - アシディファイドゾーン（風）
    - アシディファイドゾーン（火）
    - 特殊な処理が行われているため修正を保留
        - ソーントラップ
        - ブラッドサッカー
    - 未実装のため対応不要
        - ファイアーエクスパンションLv4催涙ガス
- アビスチェイサー
    - アビススクエア
- 天帝
    - 太陽の温もり
    - 月の温もり
    - 星の温もり
    - 創星の書
    - 天地万星
    - 天命落星
    - 天星
- ソウルアセティック
    - ダメージインターバルを持つ設置スキルなし
- ハイパーノービス
    - メテオストームバスター
    - ジャックフロストノヴァ
    - グラウンドグラビテーション
- 蜃気楼＆不知火
    - 苦無 -回転-
    - 苦無 -屈折-
    - 風魔手裏剣 -掌握-
    - ダメージインターバルを持たない設置スキルのため修正対象外
        - 火炎陣
- ナイトウォッチ
    - グレネーズドロッピング
    - ミッションボンバード
- スピリットハンドラー
    - ディアーブリーズ
    - 特殊な処理が行われているため修正を保留
        - イヌハッカメテオ

**Comment by fueljcl** [comment]
思った以上にありましたね…
ロジックがんばったので、スキルの修正お願いします＞＜
PWのやつを参考にしていただければ、大丈夫なはず！

**Comment by usachoco** [comment]
### 2. 修正対象スキルの特定
現状で対応可能と思われる対象は以下の11件
温もりなどいくつかのスキルは対応を保留する可能性があります

- アークメイジ
    - グラビテーションフィールド    SKILL_ID_GRAVITATION_FIELD
    - ストームガスト    SKILL_ID_STORM_GUST
    - ロードオブヴァーミリオン  SKILL_ID_LORD_OF_VERMILLION
- カーディナル
    - マグヌスエクソシズム  SKILL_ID_MAGNUS_EXORCISMUS
- エレメンタルマスター
    - クラウドキル  SKILL_ID_CLOUD_KILL
- トルバドゥール＆トルヴェール
    - シビアレインストーム  SKILL_ID_SEVERE_RAINSTORM
- バイオロ
    - デモンストレーション  SKILL_ID_DEMONSTRATION
    - デモニックファイアー  SKILL_ID_DEMONIC_FIRE
- 天帝
    - (太陽の)(月の)(星の)温もり    SKILL_ID_NUKUMORI   SKILL_ID_NUKUMORI_KABE
    - 創星の書  SKILL_ID_SOSENO_SHO
- 蜃気楼＆不知火
    - 風魔手裏剣 -掌握-     SKILL_ID_FUMASHURIKEN_SHOUAKU

**Comment by usachoco** [comment]
## 3.修正作業

- グラビテーションフィールド
固定ダメージの設置スキルどう処理するのが良いか悩んだけど解決しました
- ストームガスト & ロードオブヴァーミリオン
ほぼ完成ですがこの２スキルにはオブジェクト設置制限があるので
ディレイ０で撃ち放題にならないようにする処理を模索しています

**Comment by fueljcl** [comment]
ディレイ0ならオブジェクトはおけるけど、効果時間中にダブりが発生しないというのがあるだけかな

**Comment by usachoco** [comment]
ro4/m/js/CBattleCalcResultAll.js  の修正は 91f44b572d010799a306b35c1c484e31748fb273 で対応しました

**Comment by usachoco** [comment]
## 設置スキルの検証

### 条件
[アークメイジ Lv200 Int130 Dex130 アークワンド装備 対アイアンフィスト](https://roratorio-hub.github.io/ratorio/ro4/m/calcx.html?cx1cy1xu801110xy201.7cz11.415acz12.41j1cz13.418ecz14.41f3cz15.41gccz16.41h7cz17.41j7cz18.41jdcz19.41k6cz1a.41k6cz1b.4hM1cz1c.4hOacA1Z_1127456b89a3cA128c0cC1.ecR1.4g1cW10041cZ121)
[カーディナル Lv200 Int130 Dex130 アークワンド装備 対アヌビス](https://roratorio-hub.github.io/ratorio/ro4/m/calcx.html?cx1cy1xs801110xy201.7cz11.415acz12.41j1cz13.418ecz14.41f3cz15.41gccz16.41h7cz17.41j7cz18.41jdcz19.41k6cz1a.41k6cz1b.4hM1cz1c.4hOacA1Z_1127456b89a3cA128c0cC1.ecR1.4f4cW10041cZ121)
[エレメンタルマスター Lv200 Int130 Dex130 アークワンド装備 対アイアンフィスト](https://roratorio-hub.github.io/ratorio/ro4/m/calcx.html?cx1cy1Bt801110xy201.7cz11.415acz12.41j1cz13.418ecz14.41f3cz15.41gccz16.41h7cz17.41j7cz18.41jdcz19.41k6cz1a.41k6cz1b.4hM1cz1c.4hOacA1Z_1127456b89a3cA128c0cC1.ecR1.4g1cW10041cZ121)
[トルバドゥール Lv200 Agi130 Dex130 アーバレスト+矢装備 対アイアンフィスト](https://roratorio-hub.github.io/ratorio/ro4/m/calcx.html?cx1cy1Br801x201x201.7cz11.4162cz12.41j1cz13.418ecz14.41f3cz15.41gccz16.41h7cz17.41j7cz18.41jdcz19.41k6cz1a.41k6cz1b.4hM2cz1c.4hOacA1Z_1127456b89a3cA128c0cC1.ecR1.4g1cW10041cZ122)
[バイオロ Lv200 Str130 Int130 アイスファルシオン装備 対アイアンフィスト](https://roratorio-hub.github.io/ratorio/ro4/m/calcx.html?cx1cy1Bu80x210x2101.7cz11.4120cz12.41j1cz13.418ecz14.41f3cz15.41gccz16.41h7cz17.41j7cz18.41jdcz19.41k6cz1a.41k6cz1b.4hM1cz1c.4hOacA1Z_1127456b89a3cA128c0cC1.ecR1.4g1cW10041cZ121)
[天帝 Lv200 Str130 アビスブック装備 対アイアンフィスト](https://roratorio-hub.github.io/ratorio/ro4/m/calcx.html?cx1cy1Bv80x21011101.7cz11.4dodcz12.41j1cz13.418ecz14.41f3cz15.41gccz16.41h7cz17.41j7cz18.41jdcz19.41k6cz1a.41k6cz1b.4hM1cz1c.4hOacA1Z_1127456b89a3cA128c0cC1.ecR1.4g1cW10041cZ121)

### 単発のダメージ計算が合理的な値になっている
- ◯ グラビテーションフィールド
- ◯ ストームガスト
- ◯ ロードオブヴァーミリオン
- ◯ マグヌスエクソシズム
- ◯ クラウドキル
- ◯ シビアレインストーム
- ？ デモンストレーション
    いままでの計算機のダメージがおかしいので比較できない要検証
    ただし今までの計算式よりは精度が上がっているので一旦リリースしても良いと思う
- ◯ デモニックファイアー
- ◯ 温もり
- ？ 創星の書
    いままでの計算機のダメージがおかしいので比較できない要検証
    ただし今までの計算式よりは精度が上がっているので一旦リリースしても良いと思う

###１サイクルのダメージ計算が合理的な値になっている
- ◯ グラビテーションフィールド
- ◯ ストームガスト
- ◯ ロードオブヴァーミリオン
- ◯ マグヌスエクソシズム
- ◯ クラウドキル
- ◯ シビアレインストーム
- ◯ デモンストレーション
- ◯ デモニックファイアー
- ◯ 温もり
- ◯ 創星の書

### DPSが合理的な値になっている (1Hitダメージ / 設置型攻撃間隔)
- ◯ グラビテーションフィールド
- ◯ ストームガスト
- ◯ ロードオブヴァーミリオン
- ◯ マグヌスエクソシズム
- ◯ クラウドキル
- ◯ シビアレインストーム
- ◯ デモンストレーション
- ◯ デモニックファイアー
- ◯ 温もり
- ◯ 創星の書

### 戦闘の所要時間が合理的な値になっている
- ◯ グラビテーションフィールド
- ◯ ストームガスト
- ？ ロードオブヴァーミリオン
    持続時間 / 攻撃間隔 が割り切れずに Math.ceil しているスキル
    8 Hits = 2 回詠唱 で倒せる敵を 8 Hits と 3 回目の詠唱 で倒す計算になってる
    ただし今までの計算式よりは精度が上がっているので一旦リリースしても良いと思う
- ？ マグヌスエクソシズム
    持続時間 / 攻撃間隔 が割り切れずに Math.ceil しているスキル
    LoVと同じように詠唱が1回程度余計に計算されているようにみえる
    ただし今までの計算式よりは精度が上がっているので一旦リリースしても良いと思う
- ◯ クラウドキル
- ◯ シビアレインストーム
- ◯ デモンストレーション
- ◯ デモニックファイアー
- ◯ 温もり
- ◯ 創星の書

### スキルの多重設置の可否が考慮されている
- ◯ グラビテーションフィールド
- ◯ ストームガスト
- ◯ ロードオブヴァーミリオン
- ◯ マグヌスエクソシズム
- ◯ クラウドキル
- ◯ シビアレインストーム
- ◯ デモンストレーション
- ◯ デモニックファイアー
- ◯ 温もり
- ◯ 創星の書

### 単発スキルの戦闘継続時間がおかしくなってない
- ◯ ファイアーボルト
