### ISSUE TITLE
セット効果の定義に不備がある装備

### ISSUE THREAD

**Issue by usachoco** [roratorio-hub/ratorio#211]
Discord 経由でお知らせ頂いた情報です

> 祈りの晩鐘とイビルアイのセット効果が説明にないようです
セット効果も設定されてない？

偽神のイビルアイ側には説明が記載されていますが、
おっしゃるように祈りの晩鐘側には説明が記載されていません

**Comment by usachoco** [comment]
意図的に手を抜いた部分でした
利用者の方を混乱させてしまうのは良くないので修正予定です

## 説明
アイテムのセット効果は
セットを構成するパズルのピースのうち
どれか１つに定義があれば発動します

それを踏まえて、作業量を減らすために
ラトリオHubで追加されたアイテム、カード、エンチャントは
基本的に以下のような状態で登録されています

## 例
### 偽神のイビルアイ
【偽神のイビルアイ】＋【祈りの晩鐘(エンチャント)】を同時に装備した時
プレイヤーから受けるダメージ 5%減少
聖属性攻撃に対する耐性 + 5%
念属性攻撃に対する耐性 + 5%

### 祈りの晩鐘
偽神のイビルアイのセット効果記述無し

**Comment by usachoco** [comment]
修正方針の選択肢

### １．双方向にセット効果を定義する
メリット：本来あるべきデータ構造になるのでなんだか安心できる
デメリット：作業量が多い

### ２．アイテム説明文だけ追加する
メリット：作業量が少なくて済む
デメリット：本来あるべきデータ構造ではないので将来何か問題がおきるかもしれない

**Comment by fueljcl** [comment]
1のデメリットに、SPが二重で効果を発揮する可能性かな？

**Comment by usachoco** [comment]
Googleフォームより
>・エンチャ[天地崩壊]の説明文にダイヤ靴とのセット効果が記載されてません(効果は適用)

対応予定です

**Comment by usachoco** [comment]
## 事前調査

- セット効果が二重に発動する恐れはあるのか？
真理の解放(1245) の場合

```
w_SE = [
...
		[3820,3819,-1245],
...
		[3918,3917,-1245],
...
CardIdToSetIdMap[1245] = [1064,1099,1332,1353,1359,1388,1493,1554,1607,1618,1623,2164,2193,2194,2195,2210,2254,2272,2280,2363,2383,2385,2390];
```

**Comment by usachoco** [comment]
## 解決策

![Image](https://github.com/roratorio-hub/ratorio/assets/149866018/7820a278-5fb1-408f-9ead-8f6af8539976)
