### ISSUE TITLE
「自動で再計算する」がOFFの場合に、レジストポーションにチェックを入れたときに属性倍率が更新されない

### ISSUE THREAD

**Issue by tousei-seiso** [roratorio-hub/ratorio#313]
避難所の頃から最近まで、「アイテム(食品/他)　」でレジストポーションにチェックを入れたら、「カスタム表示＞拡張情報＞属性倍率」で表示される倍率が即時変更されていたのですが、

現在、「動作設定＞ 設定変更時に自動で再計算する」　がOFFのときは、「アイテム(食品/他)」でレジストポーションにチェックを入れても、「カスタム表示＞拡張情報＞属性倍率」で表示される倍率が「計算する」ボタンを押すまで更新されないようです。

これまでと同じ動作になるようにできれば・・・。

**Comment by usachoco** [comment]
次の更新作業で対応したいと思います
「今までと同じ挙動が維持されること」はやっぱり大事ですね
#304
