### ISSUE TITLE
拡張情報>経験値のJOBに関する表記がおかしい

### ISSUE THREAD

**Issue by usachoco** [roratorio-hub/ratorio#314]
Googleフォームからお寄せ頂いた情報です

>カスタム情報→経験値で「三次職のJob69」の%を上げていくと10.0%の時点でカンスト扱いになってしまいます。古い経験値テーブルが適用されているかも……？
[追記]三次職Job69のメッセージを送った者です。確認したところ三次職のJob1～Job59まで全部10.0%でカンスト扱いになってました。

状況確認から始めます

**Comment by tousei-seiso** [comment]
少し気になり試してみました。
３次職４次職に関わらず、ジョブの方のみ、現在のジョブレベルがいくつでもそれには関係なく、
・「１０％以上」を指定すると、「次まで」「目標」ともに表示されなくなる。
ようですね。
単純に古い経験値テーブルなのでJOBが６９などの大きな値になるとあふれるという状況ではなさそうです。
