### ISSUE TITLE
セーブしたデータが正常にロードされない

### ISSUE THREAD

**Issue by usachoco** [roratorio-hub/ratorio#33]
Googleフォームからお寄せ頂いた情報です

>スピハンのシャドウアクセがセーブ後の反映がされなくリセットされます　同時に性能カスタマイズのスキル倍率が１００％から４％になってセーブされるバグもありました。

シャドウアクセサリの事象は再現確認が取れていないので確認中です
スキル倍率が100%から4%に変化してしまう事象は再現できましたので原因の調査に入ります

**Comment by usachoco** [comment]
### 確認した事象
- 性能カスタマイズ（ステータス関連）の末尾6項目がセーブされない
追加された特性ステータスと数が合うので、割り込まれた分だけ後ろにずれて処理対象からはみ出した模様
![save](https://github.com/roratorio-hub/ratorio/assets/149866018/7b8138fe-0f1b-4d9e-86c5-d6341d2afb11)

- その他の項目は全てではないが値が変化する
![save2](https://github.com/roratorio-hub/ratorio/assets/149866018/1c8e8539-c4d0-4be8-8d48-aa3b9cb79e64)

**Comment by usachoco** [comment]
以下の理由により切り戻しパッチ 091b675d89ac2324a4ba0602dd25db38cbdd8e25 を作成しました
これにより特性ステータスのカスタマイズはできなくなりますが
正しくセーブ出来ない問題は解消されます

**切り戻ししたほうが良いと思う理由**
1. 今の形を維持したままバグだけ取れないか検討しましたが私には難しそうと判断したこと
2. 星座の塔アクセサリの時限効果実装 409cd6a1bc8d39fab8facc3b01af86a0e5d38610 により特性ステータスを増減させたいニーズが減ったこと 
3. 今まで出来ていた事ができなくなったという声が利用者から上がっていること（このIssue）

ただ 1 については他の開発者さんの解析が進んでいる可能性もあるので
一度相談してから対応を決めたいと思います

**Comment by usachoco** [comment]
やはり解析が進んでいたため
切り戻しではなくバグを取り除いた機能限定版 2e236cd2cfc43ef866f18003dd5565e0f62ea7c2 をリリースしました
セーブ・ロード機能は引き続き解析中なので Issue は開いたままにしておきます

**Comment by fueljcl** [comment]
こちら、クローズでよさそう…？

**Comment by usachoco** [comment]
クローズで大丈夫ですね！
ありがとうございました
