### ISSUE TITLE
セーブデータの名前文字数制限を拡張して欲しい

### ISSUE THREAD

**Issue by usachoco** [roratorio-hub/ratorio#363]
Googleフォームより
>・セーブデータの文字数制限をもう少し増やしてほしい(No.1～No.100の)

セーブデータの構造変更が必要だった気がします
まずは調査から

**Comment by fueljcl** [comment]
かんたんに調べた結果をDiscordの方でスレッドに記録しておきましたのでご確認くださいませ。
よろしくお願いします。

**Comment by usachoco** [comment]
おかげさまで３分で改修作業が終わりました
ありがとうございました

**Comment by fueljcl** [comment]
たまには貢献しないと…と思ってちょっとがんばりましたｗ
無事に改修できたようで何よりですっ
