### ISSUE TITLE
潜在開放に関係するスキル

### ISSUE THREAD

**Issue by usachoco** [roratorio-hub/ratorio#37]
基本情報は登録出来たので他のスキルと平行してダメージ実測値との合わせ、詠唱・ディレイなどの実装を進めていきます

### ハイパーノービス
お寄せ頂いているサンプルから計算式が導けず苦戦中  
特性ステータスや独学が0の状態でスキルLv1、Lv2の値があると良いのかもしれません  
- [ユピテルサンダーストーム](https://ragnarokonline.gungho.jp/gameguide/character/novice/hypernovice.html#skill08)
- [ヘルズドライブ](https://ragnarokonline.gungho.jp/gameguide/character/novice/hypernovice.html#skill10)
- [ナパームバルカンストライク](https://ragnarokonline.gungho.jp/gameguide/character/novice/hypernovice.html#skill12)
- [メテオストームバスター](https://ragnarokonline.gungho.jp/gameguide/character/novice/hypernovice.html#skill07)
- [ダブルボウリングバッシュ](https://ragnarokonline.gungho.jp/gameguide/character/novice/hypernovice.html#skill03)
- [メガソニックブロー](https://ragnarokonline.gungho.jp/gameguide/character/novice/hypernovice.html#skill04)

### 蜃気楼　不知火
お寄せ頂いているサンプルから計算式が導けず苦戦中  
特性ステータスが0の状態でスキルLv1、Lv2の値があると良いのかもしれません  
- [影の舞](https://ragnarokonline.gungho.jp/gameguide/character/ninja/shiranui.html#skill06)
- [影一閃](https://ragnarokonline.gungho.jp/gameguide/character/ninja/shiranui.html#skill07)
- [影狩り](https://ragnarokonline.gungho.jp/gameguide/character/ninja/shiranui.html#skill05)
- [幻術 -影縫い-](https://ragnarokonline.gungho.jp/gameguide/character/ninja/shiranui.html#skill18)
- [風魔手裏剣 -掌握-](https://ragnarokonline.gungho.jp/gameguide/character/ninja/shiranui.html#skill08)
- [風魔手裏剣 -構築-](https://ragnarokonline.gungho.jp/gameguide/character/ninja/shiranui.html#skill09)

## 実装済み
情報収集の優先度は下がりましたがサンプルが増えれば信頼度が増えますので
提供者様に無理のない範囲で頂ける情報は引き続き歓迎します

### マイスター

- [スパークブラスター]()
- [トリプルレーザー]()

### ナイトウォッチ
- [オンリーワンバレット](https://ragnarokonline.gungho.jp/gameguide/character/gunslinger/nightwatch.html#skill06)
- [スパイラルシューティング](https://ragnarokonline.gungho.jp/gameguide/character/gunslinger/nightwatch.html#skill07)
- [マガジンフォーワン](https://ragnarokonline.gungho.jp/gameguide/character/gunslinger/nightwatch.html#skill08)
- [ビジラントアットナイト](https://ragnarokonline.gungho.jp/gameguide/character/gunslinger/nightwatch.html#skill05)
- [ワイルドファイア](https://ragnarokonline.gungho.jp/gameguide/character/gunslinger/nightwatch.html#skill09)

### スピリットハンドラー
- [タイガースラッシュ](https://ragnarokonline.gungho.jp/gameguide/character/summoner/spirithandler.html#skill03)
- [タイガーハウリング](https://ragnarokonline.gungho.jp/gameguide/character/summoner/spirithandler.html#skill04)
- [タイガーストライク](https://ragnarokonline.gungho.jp/gameguide/character/summoner/spirithandler.html#skill05)

**Comment by usachoco** [comment]
# データ収集のコツ
- BaseLv、使用したスキルLv、攻撃の属性、殴った相手、ダメージ、をメモする
- 使用したスキルに影響するステータスを確認する（ATK、MATK、P.ATK、S.MATK、特性ステータスなど）
- 使用したスキルに影響する補助スキルの状態を確認する（にゃん友、照準カウンターなど）
- その他のバフの状態を確認する（手紙、ジョンダなど）

**Comment by kaoru0214** [comment]
@usachoco さん
ハイパーノービスのメガソニックブローとダブルボーリングバッシュ実測値です
https://docs.google.com/spreadsheets/d/1VTcLDH4INVXN3_t9l4BAChISARAFgIm1f9z_myOvoJE/edit#gid=299694089

**Comment by usachoco** [comment]
@kaoru0214 
ありがとうございます
そして心苦しいお願いなのですが
もし再びデータを採取していただくことが出来るなら今度は何か武器を装備して同テストをお願い出来ないでしょうか

頂いたデータから計算式を組み立ててみたのですがどうしても数字が合いません
私の銃と猫で試した経験から推察すると計算機のプログラムは素手の場合を正しくシミュレート出来ていないようです
後出し条件で恐縮ですが **素手ではなく武器を装備した状態** でサンプルを採取していただけると幸いです

**Comment by usachoco** [comment]
PR #95 で最低限のデータを追加しました

**Comment by usachoco** [comment]
Googleフォームからお寄せ頂いた情報です
```
素手でのダメージログしか取っていなかったので割愛しますが、
スピリットハンドラー物理系のスキル確認結果です。

タイガースラッシュ	1	2	3	4	5	6	7
ダメージ(%)	(2050+SkillLv*350+スピリットMLv*100+POW*5)*BaseLv/100						
強化版ダメージ(%)	(2850+SkillLv*450+スピリットMLv*150+POW*5)*BaseLv/100						
固定詠唱(ms)	500	500	500	500	500	500	500
変動詠唱(ms)	2000	2000	2000	2000	2000	2000	2000
CT(ms)	500	500	500	500	500	500	500
ディレイ(ms)	2000	2500	3000	3500	4000	4500	5000
							
タイガーハウリング	1	2	3	4	5	6	7
ダメージ(%)	(1600+SkillLv*200+スピリットMLv*50+POW*5)*BaseLv/100						
強化版ダメージ(%)	(2400+SkillLv*300+スピリットMLv*100+POW*5)*BaseLv/100						
固定詠唱(ms)	500	500	500	500	500	500	500
変動詠唱(ms)	800	1000	1200	1400	1600	1800	2000
CT(ms)	500	500	500	500	500	500	500
ディレイ(ms)	2000	2500	3000	3500	4000	4500	5000
							
タイガーストライク	1	2	3	4	5	6	7
ダメージ(%)	(300+SkillLv*100+スピリットMLv*10+POW*5)*BaseLv/100*3						
強化版ダメージ(%)	(450+SkillLv*150+スピリットMLv*20+POW*5)*BaseLv/100*3						
固定詠唱(ms)	500	500	500	500	500	500	500
変動詠唱(ms)	800	1000	1200	1400	1600	1800	2000
CT(ms)	500	500	500	500	500	500	500
ディレイ(ms)	2000	2500	3000	3500	4000	4500	5000
```

**Comment by usachoco** [comment]
全てのスキルについてのダメージ誤差が解決されていないためクローズしていませんでしたが
30日以上クローズされていないことに加え、現時点で解決のめども立っていませんので一旦クローズしたいと思います
以降は、個別のスキル修正で対応する予定です
