### ISSUE TITLE
超越グレイシアを実装する

### ISSUE THREAD

**Issue by usachoco** [roratorio-hub/ratorio#49]
超越段階を計算機に実装するのはコスパが悪いので  
通常のグレイシアとは別のアイテムとして超越グレイシアを実装する案があります
手を動かすだけの簡単な作業ですが
使っている方はそれほど多くないと思うので優先度低めで設定しておきます

**Comment by fueljcl** [comment]
超越はすでに割と流通してて、使ってる人も多いかもしれません
可能ならもう少し優先度上げた方がいいのかもしれないと思っています
（先にセーブデータもっとがんばれというご意見もあろうかと思いますが…

**Comment by usachoco** [comment]
PR #88 で追加しました

**Comment by usachoco** [comment]
Commit 17ba5b0281ff77ebea37010a80e4a35203fdbaf3 で表記を修正しました
[超越] → [★1]
念の為、更新履歴には超越グレイシア = ★1であることを記載しています

**Comment by fueljcl** [comment]
こちらはクローズ？

**Comment by usachoco** [comment]
はい、完了ですね
確認ありがとうございました
クローズします
