### ISSUE TITLE
既存の４次スキルの未実装部分

### ISSUE THREAD

**Issue by tousei-seiso** [roratorio-hub/ratorio#50]
既存の４次スキルで、CTや効果が未実装のために計算機の計算結果に反映されない部分をなんとかできないものかなあ、と思っています。

代表的で困り感大なもの：
ウインドホーク
・ゲイルストーム・・・詠唱時間「不明」、CT「不明」のため、DPSが「計算不能」のまま。カラミティゲイルによる効果も「未実装」。
・クレッシブボルト・・・詠唱時間、CT、固定詠唱０でASPD193だとASPDで連射できる計算結果になってますが、そんなわけはない気がします。カラミティゲイルによる効果も「未実装」。
・カラミティゲイル・・・効果そのものが未実装。

他職にもこういうものが残っていると思います。特に、ウインドホークのゲイルストーム、クレッシブボルト、カラミティゲイルは、３次スキルでいうところのアロスト、エイムド、アンリミですので、これがDPSも威力も効果も計算できないままなのは皆さん非常にお困まりと思います。３次スキルと計算で比較できないと、「装備を更新してアロストエイムドから移行しようか」という検討にも使えないです。

実測データを募り、詠唱時間、CT、固定詠唱については値を作り、カラミティゲイルも効果のまずはおおざっぱでも計算式を考える必要があると思います。スキルの追加より優先度が高いと感じていますが、いかがなものでしょうか？

**Comment by usachoco** [comment]
たしかに人数比が違うでしょうから既存４次職のニーズは高そうですね

まずは拡張四次に限らずスキル情報提供のお願いを計算機の表から見える場所に掲載することを考えています
その先は必要十分な情報が集まったものから順に実装するのが良さそうです
集まり具合＝ニーズの高さと受け取れます

それと並行して私自身はやはり追加出来ないアイテムが残り続ける事が気になるので
当初の予定通り[潜在解放に関連する新スキル](https://github.com/roratorio-hub/ratorio/issues/37)に当面の狙いを定めて取り組んで行くつもりです

スキル定義はある程度の解析が済んでいますので
[Wiki](https://github.com/roratorio-hub/ratorio/wiki/%E3%82%B9%E3%82%AD%E3%83%AB%5B%E6%94%BB%E6%92%83%5D%E3%81%AE%E5%AE%9A%E7%BE%A9)を見ながらスキルデータを更新してプルリクをしていただくことも大歓迎です

**Comment by tousei-seiso** [comment]
＞まずは拡張四次に限らずスキル情報提供のお願いを計算機の表から見える場所に掲載することを考えています
「スキル情報提供のお願い」良いと思います。
詠唱時間、CT、固定詠唱などの計算用に、それぞれどのようなデータをどんな形で取るといいか書いてあるといいかと思います。上がったものはそのまま私達からも見える形がとれるといいと思います。上がった情報を見ながら検討できますので。

＞スキル定義はある程度の解析が済んでいますので
了解です。

**Comment by usachoco** [comment]
ゲイルストーム、クレッシブボルトは対応済み
カラミティゲイルは #52 で引き続き管理しますので
このIssueはクローズする予定です
