### ISSUE TITLE
Clip機能の改善要望

### ISSUE THREAD

**Issue by usachoco** [roratorio-hub/ratorio#539]
Googleフォームより
>Clip機能のmemoにチェックを付け「Clip」ボタンを押下すると表示されるダイアログに対してキャンセルしてもダメージが記録されてしまうため、キャンセルを押下した際は記録されないようにしていただけないでしょうか。

**Comment by rag769** [comment]
メモ入力の有無に関係なく 1click で clip 確定は共通動作（現状維持）にして
modal ウィンドウで clip 履歴を操作できる方向で対応するのはどうでしょう？

![image](https://github.com/user-attachments/assets/5ec080db-d06a-46a4-bdd9-b6e4e80cd6e7)
- 並び順変更
- 削除
- グラフ表示（メインから出張）


とりあえず実装はしたのでPRはできますが、何かいい案ありますか？

**Comment by usachoco** [comment]
キャンセルされたときは単純に後続の処理をスキップすることを想像していましたが
ご提案いただいた方針はそれよりも更に良いと思います
ぜひ PR をお願いします！

直感的には「キャンセル」を押したら直前の操作「Clip」が取り消されるのが自然な気がしますが
かといってボタン表記を「OK/キャンセル」から「memoを入力する/memo無しで入力する」にするのも野暮ったいですし
「間違ってClipしてしまったデータをグラフに記録したくない」という動機が結果的に満たされるなら良いのでは無いかと思います
