### ISSUE TITLE
固定詠唱、クールタイムのデータの取り方

### ISSUE THREAD

**Issue by tousei-seiso** [roratorio-hub/ratorio#54]
自分でデータ取りを始めてみました。クレッシブボルトの最大速度連射をしながら動画を撮影し、可能な限り時間間隔のゲージを引き伸ばして映像を見ながらやってみました。

１）動画上スキル発動開始（ゲージと魔法陣出現）～ゲージ１００％でゲージが消えるまで
２）ゲージが消えてから、命中の瞬間まで（ダメージ表示開始の瞬間）

１）２）それぞれに時間がかかっています。２点データ収集上必要な質問があります。

質問１
おそらく、１）自体は固定詠唱の時間、そして、１）完了から２）完了までは、モーションとエフェクトに必要とする時間ではと思います。ですので、固定詠唱のデータとしては１）にかかった時間で良いと思いますが、これで合ってますか？

質問２
この場合、クールタイムの計算は、どこからどこまでの時間で取るとよいでしょうか。１）完了から、次の１）開始までで良いでしょうか？

ちなみに、動画で時間ゲージを動かしながら見て計算する関係もあり、求められる値はずれます。ずれた値から「恐らくこの値」と考えて、まずは固定詠唱とクールタイムを実装してみようと思います。

提案１
スキル情報としてよせられたデータを活用出来るように、 github 閲覧者が見ることが出来るよう、どこかに公開していただけないでしょうか？（ google ドライブの機能に不案内ですので、もし現状のまま誰でもフォームから投稿された情報が閲覧できるのであれば、その方法をご教示くだされば協力できる方も増えると思います。）

**Comment by usachoco** [comment]
ありがとうございます

私もROの仕様について詳しいわけではないので断言出来ないのですが
仰るとおり詠唱バーが出現してから消えるまでの時間を測定する方針で良いと思っています

クールタイムはアイコンの色に着目するのが良いと考えていました
クレッシブボルトのアイコンが暗くなり、時計回りのエフェクトを伴って明るくなっていきますよね
その時計がどれぐらいの時間で一周してアイコンが完全に明るくなるのかを測定する方針で良いと思っています

Googleフォームからお寄せ頂いた情報を今はDiscordのチャンネルに共有しています
Github上からも見れるように適切な公開場所を考えますね

**Comment by tousei-seiso** [comment]
固定詠唱について判断ありがとうございます。

クールタイムはアイコンの色に着目するのが良いと考えていました
クレッシブボルトのアイコンが暗くなり、時計回りのエフェクトを伴って明るくなっていきますよね
その時計がどれぐらいの時間で一周してアイコンが完全に明るくなるのかを測定する方針で良いと思っています

なるほど、その方法も良いですね。比較してみましたが、上記の２）（詠唱ゲージが消えてから命中の瞬間まで）と同じ時間帯でアイコンが完全に明るくない状態になっていましたので、計測時間は正しく取れているようです。アイコンの明るさ、今後の検証に活用してますね。いい方法をありがとうございます。

＞ついでにディレイについては
＞クレッシブボルト以外のスキルアイコンが暗くなってから明るくなるまでの時間を測定するのが良いと思っています
ディレイカットできていない領域での検証の際に参考にしておきます。

**Comment by usachoco** [comment]
このIssueはWikiに情報をまとめた後にクローズする予定です

**Comment by usachoco** [comment]
WikiにまとめましたのでこのIssueをクローズします

https://github.com/roratorio-hub/ratorio/wiki/%E8%A9%A0%E5%94%B1%E3%83%BB%E3%83%87%E3%82%A3%E3%83%AC%E3%82%A4%E3%83%BB%E3%82%AF%E3%83%BC%E3%83%AB%E3%82%BF%E3%82%A4%E3%83%A0%E3%81%AE%E6%B8%AC%E5%AE%9A%E6%96%B9%E6%B3%95
