### ISSUE TITLE
「想定外の錐効果演算」エラー

### ISSUE THREAD

**Issue by usachoco** [roratorio-hub/ratorio#567]
Google フォームより
>計算機の運営、ありがとうございます。いつもお世話になっております。
「想定外の錐効果」が出ましたのでご連絡差し上げます。以下、URLです。
お忙しいとは思いますが、無理のない範囲でこれからもお願いいたします。

[URL1](https://roratorio-hub.github.io/ratorio/ro4/m/calcx.html#OBJID_SAVE_BLOCK_MIG?cx1cy1Ap8gmiqJutoq.47.3cz21001-jmnDp82zigI6al0cz22001_j617svbpEonJfP8J2cz23001-bxMqKjK5tupbdz2cz24001_hif3U2z6y9r7wjH5cz25001-hiN2AFDaCxwQe1cz26001_b_x1Xe2oZ94Opgsb2cz27001VjfFhNoNvZv3Opcz28.31jc6DJ3cz29.319Z2Licz2a001xhhgIU0cL0cz2b.4ho1cz2c.4hpacA1Z_1127456b89a3cA128c0cC1.ecD1.eqc00q1a35cK103.bcM1.aJqeiH92cR200pb1i9cV1.9w.5acW10041cZ121)

[URL2](https://roratorio-hub.github.io/ratorio/ro4/m/calcx.html?cx1cy1wr80rmqOocs-1.7cz21001vbQP1kiiyjp6D5Ekcz22001lbSU1vnyxkns5cz23.3GjlDpx6pf1cz24001-hsBeIcCWsaCk_ccz25.418ccz26001kjfJiEsytf5cz27.419ncz280w1-j8CG4wpE8C_hob9cz29001_9Z2LiVgEsAabf2incz2a001_hl9fI4mRyjiLzC3qcz2b.4ho1cz2c.4hpacA1Z-3127456b89a3cA128c0cB1.q9u0w01w6EqllFll5cC1.ecD1.f40faa55acK102.7g.31cM1.aLlH4u4acR2.41fbcW1005gD2cZ121)

[URL3](https://roratorio-hub.github.io/ratorio/ro4/m/calcx.html?cx1cy1wsCmpteOos4Rz2.3P00cz21.4j2P1cz22.319zi77cz23001VbRRxafBbucblscz24.49Mgcz25.4hf5cz26.4hh6cz27.4jjj7cz28.4bP57cz29001_hnm4S8pECwnaA1Ikcz2a001xhhg4O0cL0cz2b.4ho1cz2c.4hpacz2d.4hpgcz2e.4hphcz2f.4hpfcz2g.4hpicz2h.4hpjcA1Z_1127456b89a3cA128c0cA1fgfdejg1cC1.dhbcD1.f62759aaaacL1.6hr1cM1.a_qfhp8j1cR2.41i9cW10041cZ121)

**Comment by usachoco** [comment]
本来紛れ込むはずがない `#OBJID_SAVE_BLOCK_MIG` が気になりますが
`#OBJID_SAVE_BLOCK_MIG` を消してもエラーは消えません
なぜ `#OBJID_SAVE_BLOCK_MIG` が紛れ込んだのかを調べるのが良さそうです

**Comment by usachoco** [comment]
オートスペルを２つ以上設定した状態で
錐効果を取った場合に発生する不具合であることを確認しました
この問題は避難所でも同様に発生します

**Comment by rag769** [comment]
> 本来紛れ込むはずがない `#OBJID_SAVE_BLOCK_MIG` が気になりますが `#OBJID_SAVE_BLOCK_MIG` を消してもエラーは消えません なぜ `#OBJID_SAVE_BLOCK_MIG` が紛れ込んだのかを調べるのが良さそうです

ページ下部の「今後は最新版のセーブ・ロード機能をご利用下さい」のリンクを踏んだんだと思います

> 最新版のセーブ・ロード機能 => https://roratorio-hub.github.io/ratorio/ro4/m/calcx.html#OBJID_SAVE_BLOCK_MIG

**Comment by usachoco** [comment]
ありがとうございます
そのタイミングで location.href が上書きされてしまうわけですね
錐＋オートスペル周りの修正と合わせて対応しようと思います

**Comment by usachoco** [comment]
問題箇所は ro4/m/js/head.js の BattleCalc999Core() にある以下のコードです

![Image](https://github.com/user-attachments/assets/537dc280-2d83-4679-835f-888430ca83be)

気になる点が２つあります

1. n_AS_MODE は該当スキルがオートスペルか否かを判定するスイッチと思われますが n_AS_MODE に値を代入するコードは ro4/m/js/calcautospell.js の到達不能位置にあり、必ず 0 の状態でこの判定文が処理されます。意味がない判定条件なので取り外しても構わないか？

2. n_A_QUAKE_KIRI は錐効果によるダメージ増加Buffの倍率が格納される変数です。イフリートカードで攻撃手段にEQを設定した場合はこれが 0 であり、オートスペルに EQ を設定した場合は 0 以外の値が代入されています。この差異はどうして生まれるのか？

**Comment by usachoco** [comment]
オートスペルであるか否かによらずダメージ計算は 
BattleCalc999Body()
で共通処理が行われます

まずはじめに ro4/m/js/head.js@607 から BattleCalc999Body() に遷移します
これはオートスペルではありません

それが終わったら ro4/m/js/head.js@620 でオートスペル配列の有無をチェックし
オートスペルを計算する必要がある場合は再び BattleCalc999Body() に遷移します

ですから 620 行以下で「この計算はオートスペルである」ことを教えることにします

![image](https://github.com/user-attachments/assets/7cc5141d-220a-4528-8552-03c43363b9d3)

**Comment by usachoco** [comment]
あわせて、エラーハンドリングのアラート位置を少し変えます
既存のバージョンでは [最小ダメージ、平均ダメージ、最大ダメージ] の配列を回すループの中でアラートが呼び出されており
これでは無駄に何度もモーダルダイアログを表示する問題があります

以下の様に変更します

![image](https://github.com/user-attachments/assets/2e106587-064f-4c22-a9f9-185eb2ef6104)

**Comment by usachoco** [comment]
#OBJID_SAVE_BLOCK_MIG の修正対応をわすれないように

**Comment by usachoco** [comment]
b0aa40e4fed695cc4a8b10e95fcaa5b31fd9f23f で対応済みです
