### ISSUE TITLE
出来ることならカードの並び順を改善したい

### ISSUE THREAD

**Issue by usachoco** [roratorio-hub/ratorio#61]
気になってはいたのですが利用者の方からもご意見を頂いたのでIssueに追加しました

>Waterfox（Firefox）の件ですが、カード初期化は起きなくなりました。ありがとうございます。
ただ、代わりにカードの並び順がおかしい（読み方に関わらず記号・英字のものは上に、漢字のものは下になる）のがデフォルトになってしまったようです。
前避難所とは違う並びなのでおかしいと感じてしまうのですが、もしこれが仕様であるという事であれば慣れるように努めます。

避難所のプログラムではカードを手動でソートしているのですが、もちろんその際にはツールを使っていたはずです
Debugディレクトリ以下のツール群の中にソートプログラムが見つかるようなら、それを参考にして避難所と同じソートが再現出来るかもしれません

**Comment by usachoco** [comment]
説明が不足していると思いましたので図解です

# 避難所とHubのデータの違い
![image](https://github.com/roratorio-hub/ratorio/assets/149866018/9ecd4485-df73-4591-b6ad-0bf2dd1944d1)

# Hubのデータのソート手順
![image](https://github.com/roratorio-hub/ratorio/assets/149866018/9fabe694-3bc4-4c64-8a2f-846f56217806)

**Comment by rag769** [comment]
#65

**Comment by usachoco** [comment]
避難所のカードの並びをほぼ再現出来ていることを確認出来ましたのでクローズします
