### ISSUE TITLE
シャドウ装備の計算順に疑義あり

### ISSUE THREAD

**Issue by usachoco** [roratorio-hub/ratorio#647]
Google フォームより
>"動作設定で「自動再計算」を『全ての項目変更時に自動で再計算する』として、シャドウ装備のオプションの種類を変えた時、再計算にはオプションを切り替える前の値が使われているようです。（画面表示は 0 になっていますが、再計算の後に 0 になっている？）
例えばアクセで MaxHP+ 500 にしてから、オプションを火力の特性ステに変えるととてもいいダメージがでます(笑)"

**Comment by usachoco** [comment]
再現確認できました

### 1. MaxHP+500のシャドウを付ける
平均ダメージは14M
![Image](https://github.com/user-attachments/assets/cc8610c8-01c3-40b2-9769-e10cf3475d9c)

### 2. その後オプションをP.Atkに変更する
平均ダメージが60Mになる
![Image](https://github.com/user-attachments/assets/1aafed06-0d5a-4d5b-8751-2cc82893dc9c)

**Comment by fueljcl** [comment]
Autocalc()が呼び出されて、計算したあとに表示の補正が行われているからのようにみえます。
calc()の最初の方でデータを補正せずに収集しているため、以前のデータを参照しているからかな？

**Comment by usachoco** [comment]
コメントありがとうございます

StAllCalc() // ステータスの再計算
calc() // ダメージの再計算
AutoCalc() // calc()のラッパー関数

の３つを連動させる際に StAllCalc() → calc() の順番で呼び出さなければならないところ
シャドウ装備の選択欄に無理やり OnChange = "AutoCalc()" を差し込んだせいで
この呼び出し順が守られなくなってしまったのですね

---

AutoCalc()実装時に `OnChange="AutoCalc()"` を無理やり差し込んだ
https://github.com/roratorio-hub/ratorio/blob/6b563099e3a8e8049b3409c9caf9f982e52b4eee/ro4/m/calcx.html#L1042-L1043

でも、シャドウ装備はもともとonChangeShadow()で更新する仕様だった
https://github.com/roratorio-hub/ratorio/blob/6b563099e3a8e8049b3409c9caf9f982e52b4eee/ro4/m/js/CShadowEquipController.js#L136-L140

だから、本来はonChangeShadow()のこの部分を改修しなければならない
https://github.com/roratorio-hub/ratorio/blob/6b563099e3a8e8049b3409c9caf9f982e52b4eee/ro4/m/js/CShadowEquipController.js#L317-L323
