### ISSUE TITLE
データセーブしたものをロードすると矢が未装備になる

### ISSUE THREAD

**Issue by tousei-seiso** [roratorio-hub/ratorio#71]
避難所のときからです。
他職は知りませんが、アーチャー系では、矢の装備状態が保存されません。
避難所の開発者様は、当面なおせないとおっしゃってましたが、他職のキャノンボールなどの装備状態は当然保存されますので、矢の装備状態も保存されるようになれば毎回再設定せずにすみますので issue に上げておきます。

**Comment by fueljcl** [comment]
こちらは、https://github.com/roratorio-hub/ratorio/pull/70/commits/8935c087c3265267cf0b805695925265fbae308a にて対応しました

to うさちょこさん
クローズしてよければ、マスターにマージしたタイミングでクローズをお願いします

**Comment by tousei-seiso** [comment]
少し調べてみました。消費する装備には２系統あって、「武器タイプ」欄で設定する職と、「攻撃方法」欄で設定する職があります。

１）「武器タイプ」欄で設定する職：アーチャー系（弓：矢）、シーフ系（弓：矢）、ガンスリンガー系（銃：銃弾）
２）「攻撃方法」欄で設定する職：メカニック系（キャノンボール）、忍者系（苦無）

現状、１）の「武器タイプ」欄で設定する職は、矢と銃弾があり、どちらも装備状態が保存できません。

２）の「攻撃方法」欄で設定する職には、キャノンボールと苦無があり、どちらも装備状態が保存されます。

１）のタイプがダメなようです。

**Comment by tousei-seiso** [comment]
> こちらは、[8935c08](https://github.com/roratorio-hub/ratorio/commit/8935c087c3265267cf0b805695925265fbae308a) にて対応しました
> 
> to うさちょこさん クローズしてよければ、マスターにマージしたタイミングでクローズをお願いします

うーん、どうしてだろう・・・ dev branch を clone して、 8935c08 修正の入っているのを確認し、ローカルでテストしましたが、WHにエルフの矢を装備し保存・ロードで矢が消えます。

**Comment by fueljcl** [comment]
なんだってー！
こちらでも確認してみますね

**Comment by fueljcl** [comment]
いったん、エラーが出る問題については解決したので、進めてください
その上で矢が保存できない問題は別問題のようなので、場合によってはセーブデータの拡張も考慮に入れつつ
新たな対応をしたいと思います

**Comment by usachoco** [comment]
#72 で対応していただきました
クローズ予定です
