### ISSUE TITLE
計算履歴グラフ機能で分析できないケースがある

### ISSUE THREAD

**Issue by usachoco** [roratorio-hub/ratorio#724]
Googleフォームより

>現状のDPS/確殺数の折れ線フラグですが、1shotまたは１サイクルあたりのダメージも追加いただけないでしょうか。
ダメージ計算式未実装スキルをシミュレートする際、現状のグラフはDPS/確殺数ともに0であるため使いづらく感じております。
せめて単発当たりのダメージだけでも比較できれば便利かと思いますので、ご検討をお願いいたします。

**Comment by usachoco** [comment]
これはグラフ機能をアップデートするのではなく
各スキルのほうを直していくほうが良い気がします

DPSが0になるスキルとは詠唱・ディレイが未設定のスキルだと思うので
とりあえずそれを設定してしまう方針です

**Comment by rag769** [comment]
グラフにだけ手を入れました。
（モーダルの表は横幅が面倒なので現状維持）

追加したデータ
* 「通常」= 通常(1Hit) の 平均値 で .BTLRSLT_DAMAGE_TOTAL（NNN x NNN だと数値化が面倒なので）
* 「1ｻｲｸﾙﾀﾞﾒ」= 1ｻｲｸﾙﾀﾞﾒ の 平均値 で BTLRSLT_DAMAGE_DETAIL（こちらでないと1サイクルになってない?ので） 

両方追加表示すると（個人的に）ゴチャゴチャするので、「1ｻｲｸﾙﾀﾞﾒ」は非表示にしています。（#88）
ラベルや色は良い感じに調整してください（#66：const data）

初期表示
![image](https://github.com/user-attachments/assets/93386908-ccfd-43e2-b372-9f24a56006b8)

凡例をクリックで表示/非表示切替
![image](https://github.com/user-attachments/assets/81fc4aea-f7f9-4119-a130-c985aece761c)

対応済ファイル
[calchistory.zip](https://github.com/user-attachments/files/18090690/calchistory.zip)

**Comment by usachoco** [comment]
ありがとうございます
動作確認させていただきました
本日本番にマージさせていただきます
