### ISSUE TITLE
保存済みのキャラデータにカードのソートが反映されない

### ISSUE THREAD

**Issue by tousei-seiso** [roratorio-hub/ratorio#9]
1/1 の修正、「カードのドロップダウンリストをソート」ですが、
既に以前のドロップダウン順のときに作成して保存したキャラクターデータをロードした場合は適用されないようです。
エクストラジョーカーカードで試しましたが、ドロップダウンの一番下のままでした。

今後カードデータのソート状態が再度編集された場合も、保存してあったデータのカードスロットの並びは編集前のままと思います。（関わって、今後カードデータの追加・修正があった場合に、既に保存済みのキャラデータが対応できるか少し気になります。）

**Comment by usachoco** [comment]
ありがとうございます。
特定のボタンを押して画面を更新した時にソートするようにしたので、私がトリガーとなるボタンを拾い忘れているのだと思います。
修正予定に入れておきます。

**Comment by usachoco** [comment]
- 画面上部のロードボタン
- 画面上部のURL入力ボタン
- 画面下部のURL入力ボタン
この全てにカードのソート関数をトリガーする処理を追加しました
ada2810298fe2eb64a8486d900e48df6491bb1af
