### ISSUE TITLE
セーブ・ロードの不具合

### ISSUE THREAD

**Issue by tousei-seiso** [roratorio-hub/ratorio#92]
現在、セーブ、ロードが正常に動作しなくなっています。

（再現手順１）
１）空の番号に新規に職業と装備を入力して「セーブ」
２）セーブしたデータをそのまま「ロード」　ー＞　※edge の場合１回めのロードはOK。 firefox だと１回目のロード時点で、他のステータスや装備は入力した状態だが職業欄の見た目が「ノービス」になる。
３）edge でも、もう一度ロードボタンを押す　ー＞　職業が見た目「ノービス」になりリストを開くとセーブした職が選択という状態になり、武器は「素手」になる。それ以降、他の番号にセーブしたデータもロードされなくなる。

（再現手順２）
１）何らかのデータをロードする　ー＞　ロードはされるが、「名前入力可能（２０文字まで）」の入力欄に、ロードしたセーブデータに付けた文字列が入っていない状態でロードされる。
２）２回めのロードを押すと、「ノービス」「素手」となる。
３）それ以降ロードもセーブもできなくなる。
※ edge, firefox 共にこうなります。

追記：
・ウインドホークで確認しました。

**Comment by usachoco** [comment]
ありがとうございます
1/17の朝にmasterにマージする予定です
その後、このIssueもクローズいたしますね
